### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by parktool** [surprisehighway/craft-avataxtaxadjuster#4]
Hi, just wondering what your plans are as far as updating this plugin for Craft 3 & Commerce 2. Thanks!

**Comment by siffring** [comment]
Hi @parktool we're definitely planning to update it to Craft 3 / Commerce 2. Hoping to have it around the time Commerce 2 is released.

If you have a hard deadline we can try to work with you. Email me at jason@surprisehighway.com.

**Comment by boldenamsterdam** [comment]
Hi @siffring ,

We are wondering if there are any updates about releasing this plugin for Craft 3?

Cheers!

**Comment by siffring** [comment]
@boldenamsterdam Yes, we're definitely planning to get it updated. Do you have a specific timeline for a project?

**Comment by siffring** [comment]
@parktool @boldenamsterdam FYI we're almost ready to start testing the Craft 3 / Commerce 2 version of this plugin. Are you interested in beta testing?

**Comment by imagehat** [comment]
@parktool @boldenamsterdam - We have a new Craft 3 / Commerce 2 version available now if you'd like to try it out: https://github.com/surprisehighway/craft-avatax

We'd welcome (and appreciate) any feedback, issues, or ideas for enhancement!
